### ISSUE TITLE
Arduino 1.8.4 not showing added boards

### ISSUE THREAD

**Issue by K2AAE** [stm32duino/BoardManagerFiles#10]
I 'upgraded' to 1.8.4 and then added https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json 
to the preferences.txt file with the IDE, inside of board manager there is no STM libraries to load, nothing shows up.
How do I delete this?
Library Manager is not Board Manager! dah..

**Comment by fpistm** [comment]
Hi @Airheadbit,
It should be available in the 'contributed' section.
Which OS you use?
In the Arduino console have you got some error message? 
Have you got several url in the Additional url field?
Have you try to delete local files of Arduino IDE? (open preferences window then click on  preferences.txt link. Close Arduinon IDE then delete all package_stm_index.json* files)

I'm running also with 1.8.4 on Windows and Linux and I do not have any issue.

**Comment by fpistm** [comment]
Any news @Airheadbit?

**Comment by Testato** [comment]
I think he is confusing, but he solved the problem itself, please read the last part of his comment:

> How do I delete this?
> Library Manager is not Board Manager! dah..

He ask here how delete this issue, because he had solved the problem :-)

You can close this issue ;-)

**Comment by fpistm** [comment]
Thanks @Testato. I did not saw he has updated his first comment :)
