### ISSUE TITLE
no update,, f103c6 32k not showing 

### ISSUE THREAD

**Issue by bramnyadewi007** [stm32duino/BoardManagerFiles#16]

**Comment by fpistm** [comment]
BluePillF103 C6 will be in the next release of the core: 1.5.0.
It is currently available only thanks the repo.
Release should come in the coming weeks.

**Comment by Testato** [comment]
C6 ?
32kB ?

Bluepill is on C8/CB and it have 64kB/128kB

**Comment by fpistm** [comment]
Yes, @Testato. It seems that some BluePill sold as C8 are in fact C6.
http://stm32duino.com/viewtopic.php?f=28&t=4468&hilit=fake

**Comment by fpistm** [comment]
Close it. Question about variant availability. --> Next release 1.5.0
