### ISSUE TITLE
could'nt recieve integers at master from slave

### ISSUE THREAD

**Issue by DarXSouls** [stm32duino/BoardManagerFiles#19]
well in examples the character array works pretty good..., but when modified to send integer there is no serial print ... gets struck at some unknown point

**Comment by fpistm** [comment]
Hi  @DeadSHoT555 
This place is for issue with BoardManager, so do not see any link with board manager.
I guess you have an issue with the core, so please submit issue here 
https://github.com/stm32duino/Arduino_Core_STM32/issues

Also be more precise about your issue (core version, sketch example,...), you can follow the issue template to help us to help you.
