### ISSUE TITLE
transferring data from stm32 nucleo to nodemcu 

### ISSUE THREAD

**Issue by gauri8427** [stm32duino/BoardManagerFiles#23]
I am trying to send data using rx tx pins from stm32 board to nodemcu, but no data is received on nodemcu. But if try the same for arduino and nodemcu the data is being easily transferred. So there any library to support connection between the two boards (stm32 and nodemcu esp8266). Please help. I tried opening stm32duino forum but it is unaccessible.

**Comment by fpistm** [comment]
Hi @gauri8427,
currently the forum is down, we do our best to get one up and running but this could take some time.
This repository is for BoardManager issue.
Please open a new one in the STM32 core repo and provide all relevant info without those info, we will not be able to help you as only safid:

> rx tx pins from stm32 board to nodemcu

would not help.
