### ISSUE TITLE
Using my own link in the "Additional Boards Managers URLs" field:

### ISSUE THREAD

**Issue by Erik-Koning** [stm32duino/BoardManagerFiles#28]
Hello,

Ive followed the information [Here](https://github.com/stm32duino/Arduino_Core_STM32#getting-started)  in the Arduino_Core_STM32 repo readme to create my own board variant in a new sub-folder in the "variant" folder. How do you recommend i install this new board variant into the arduino IDE so I can make continues changes and testing? 
I don't want to make a pull-request of my changes and have you regenerate the package_stm_index.json, because I would like to play with the options and other define variables that configure my new board. This [arduino thread](https://forum.arduino.cc/index.php?topic=457405.0) has some valuable help on the topic but I think I need a bit more info that pertains to STM first before i can generate my own package_stm_index.json to include in the "Additional Boards Managers URLs" field. 
In the package_stm_index.json file What is this tar.bz2 file here: "url": "https://github.com/stm32duino/Arduino_Core_STM32/releases/download/1.8.0/STM32-1.8.0.tar.bz2" ?
And how can i generate this tar.bz2 file?

**Comment by fpistm** [comment]
Hi @Erik-Koning 
this is simply an archive of the core. You can see the Makefile which create it.
https://github.com/stm32duino/BoardManagerFiles/blob/2413989d216699bcc8ec337e604c498604f7e7d5/STM32/src/Makefile#L39

If you want manage your own package, the best bet is to create your one and reference the official one. Like this you will only have to maintain your customization:
https://github.com/stm32duino/wiki/wiki/Custom-board-based-on-a-core

Please for further support/question use the forum: www.stm32duino.com
