### ISSUE TITLE
Bluepill target

### ISSUE THREAD

**Issue by Testato** [stm32duino/BoardManagerFiles#3]
The bluepill board use a F103C8/CB mcu and it is the most famous and cheeper stm32 development selled at only 2€

I suggest to support it from the beginning in this project.
http://www.ebay.it/itm/1pcs-STM32F103C8T6-ARM-STM32-Minimum-System-Development-Board-Module-Arduino-/201414966215?hash=item2ee5447bc7:g:X-oAAOSw6BtVVACk

**Comment by rogerclarkmelbourne** [comment]
This is already supported
