### ISSUE TITLE
How to add STM32f412ZGT6 board in the Arduino IDE board manager?

### ISSUE THREAD

**Issue by vviicckkyy55** [stm32duino/BoardManagerFiles#31]
I want to use Arduino IDE for STM32f412ZG for driving a led strip. I tried installing STM32 core in Arduino IDE but STM32f412ZGT6 is not available there. Can anybody help me with this issue? I want to have STM32f142ZGT6 as an option in the board manager.

**Comment by fpistm** [comment]
Hi @vviicckkyy55 
They are several way to do this:
https://github.com/stm32duino/wiki/wiki/Add-a-new-variant-%28board%29
or 
https://github.com/stm32duino/wiki/wiki/Custom-board-based-on-a-core

You can have a look at the Generic_F412Rx variant which I guess should be closed to the ZG.

For questions please do not open an issue. You used the forum and this is the best way to get support.
https://www.stm32duino.com/viewtopic.php?f=12&t=618
