### ISSUE TITLE
Problems with Variant_h

### ISSUE THREAD

**Issue by nicoverduin** [stm32duino/BoardManagerFiles#34]
HI,
I use the Sloeber-IDE 4.4 from Jantje. If I use the old deprecated package of STM32duino 1.9.0 it works fine. Now I am using the new 2.0.0 and it seems that the variant.h is not working quite corectly. I has a line #include VARIANT_H where this variable is substituted in the right variant include file. The compiler complains that it cannot process the include statement.
If I add \" in front and at the end of the string, all works fine.

**Comment by nicoverduin** [comment]
The cause is in a file called  sloeber.txt in the folder : D:\Sloeber_4.4\arduinoPlugin\packages\STMicroelectronics\hardware\stm32\2.1.0.

 I modified the line : 

build.info.flags=-D${build.series} -DARDUINO=${runtime.ide.version} -DARDUINO_${build.board} -DARDUINO_ARCH_${build.arch} "-DBOARD_NAME=\"${build.board}\"" -DVARIANT_H="${build.variant_h}"

into 

build.info.flags=-D${build.series} -DARDUINO=${runtime.ide.version} -DARDUINO_${build.board} -DARDUINO_ARCH_${build.arch} "-DBOARD_NAME=\"${build.board}\"" -DVARIANT_H=\""${build.variant_h}\""

Now it works like a charm
Regards
Nico

**Comment by fpistm** [comment]
This is linked to sloeber so open an issue to it.
