### ISSUE TITLE
Error Downloading https://github.com/stm32duino/BoardManagerFiles/raw/main/STM32/package_stm_index.json

### ISSUE THREAD

**Issue by saravanan6046** [stm32duino/BoardManagerFiles#36]
![image](https://user-images.githubusercontent.com/24777563/150721890-0cae588c-d141-40bf-964e-8c0bc7954504.png)

**Comment by fpistm** [comment]
Hi @saravanan6046 
The json you try to  use is deprecated, you should use this one:
https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json

About the issue it seems related to the new Arduino IDE version. Same file works fine with previous version.
As it is deprecated I will not try to fix this moreover there is no "<" in this file so don't know what could be wrong.
Moreover as this file is deprecated it will be removed. It was kept temporary to warn user about the deprecation.

**Comment by fpistm** [comment]
Seems related to https://github.com/arduino/Arduino/issues/7982
