### ISSUE TITLE
Detecting libraries used... recipe.preproc.macros pattern is missing

### ISSUE THREAD

**Issue by nagarajgollar** [stm32duino/BoardManagerFiles#41]
Hi,

i am getting below error while compiling in arduino ide

Arduino: 1.8.19 (Windows 10), Board: "Nucleo-64, Nucleo F401RE, Mass Storage, Enabled (generic 'Serial'), None, Low/Full Speed, Smallest (-Os default), None, Newlib Nano (default)"
C:\Users\amare\Downloads\arduino-1.8.19-windows\arduino-1.8.19\arduino-builder -dump-prefs -logger=machine -hardware C:\Users\amare\Downloads\arduino-1.8.19-windows\arduino-1.8.19\hardware -hardware C:\Users\amare\AppData\Local\Arduino15\packages -tools C:\Users\amare\Downloads\arduino-1.8.19-windows\arduino-1.8.19\tools-builder -tools C:\Users\amare\Downloads\arduino-1.8.19-windows\arduino-1.8.19\hardware\tools\avr -tools C:\Users\amare\AppData\Local\Arduino15\packages -built-in-libraries C:\Users\amare\Downloads\arduino-1.8.19-windows\arduino-1.8.19\libraries -libraries C:\Users\amare\OneDrive\Documents\Arduino\libraries -fqbn=STMicroelectronics:stm32:Nucleo_64:pnum=NUCLEO_F401RE,upload_method=MassStorage,xserial=generic,usb=none,xusb=FS,opt=osstd,dbg=none,rtlib=nano -ide-version=10819 -build-path C:\Users\amare\AppData\Local\Temp\arduino_build_51149 -warnings=none -build-cache C:\Users\amare\AppData\Local\Temp\arduino_cache_134155 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.STM32Tools.path=C:\Users\amare\AppData\Local\Arduino15\packages\STMicroelectronics\tools\STM32Tools\2.1.1 -prefs=runtime.tools.STM32Tools-2.1.1.path=C:\Users\amare\AppData\Local\Arduino15\packages\STMicroelectronics\tools\STM32Tools\2.1.1 -prefs=runtime.tools.xpack-arm-none-eabi-gcc.path=C:\Users\amare\AppData\Local\Arduino15\packages\STMicroelectronics\tools\xpack-arm-none-eabi-gcc\10.3.1-2.3 -prefs=runtime.tools.xpack-arm-none-eabi-gcc-10.3.1-2.3.path=C:\Users\amare\AppData\Local\Arduino15\packages\STMicroelectronics\tools\xpack-arm-none-eabi-gcc\10.3.1-2.3 -prefs=runtime.tools.CMSIS.path=C:\Users\amare\AppData\Local\Arduino15\packages\STMicroelectronics\tools\CMSIS\5.7.0 -prefs=runtime.tools.CMSIS-5.7.0.path=C:\Users\amare\AppData\Local\Arduino15\packages\STMicroelectronics\tools\CMSIS\5.7.0 -verbose C:\Users\amare\Downloads\arduino-1.8.19-windows\arduino-1.8.19\examples\01.Basics\Blink\Blink.ino

C:\Users\amare\Downloads\arduino-1.8.19-windows\arduino-1.8.19\arduino-builder -compile -logger=machine -hardware C:\Users\amare\Downloads\arduino-1.8.19-windows\arduino-1.8.19\hardware -hardware C:\Users\amare\AppData\Local\Arduino15\packages -tools C:\Users\amare\Downloads\arduino-1.8.19-windows\arduino-1.8.19\tools-builder -tools C:\Users\amare\Downloads\arduino-1.8.19-windows\arduino-1.8.19\hardware\tools\avr -tools C:\Users\amare\AppData\Local\Arduino15\packages -built-in-libraries C:\Users\amare\Downloads\arduino-1.8.19-windows\arduino-1.8.19\libraries -libraries C:\Users\amare\OneDrive\Documents\Arduino\libraries -fqbn=STMicroelectronics:stm32:Nucleo_64:pnum=NUCLEO_F401RE,upload_method=MassStorage,xserial=generic,usb=none,xusb=FS,opt=osstd,dbg=none,rtlib=nano -ide-version=10819 -build-path C:\Users\amare\AppData\Local\Temp\arduino_build_51149 -warnings=none -build-cache C:\Users\amare\AppData\Local\Temp\arduino_cache_134155 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.STM32Tools.path=C:\Users\amare\AppData\Local\Arduino15\packages\STMicroelectronics\tools\STM32Tools\2.1.1 -prefs=runtime.tools.STM32Tools-2.1.1.path=C:\Users\amare\AppData\Local\Arduino15\packages\STMicroelectronics\tools\STM32Tools\2.1.1 -prefs=runtime.tools.xpack-arm-none-eabi-gcc.path=C:\Users\amare\AppData\Local\Arduino15\packages\STMicroelectronics\tools\xpack-arm-none-eabi-gcc\10.3.1-2.3 -prefs=runtime.tools.xpack-arm-none-eabi-gcc-10.3.1-2.3.path=C:\Users\amare\AppData\Local\Arduino15\packages\STMicroelectronics\tools\xpack-arm-none-eabi-gcc\10.3.1-2.3 -prefs=runtime.tools.CMSIS.path=C:\Users\amare\AppData\Local\Arduino15\packages\STMicroelectronics\tools\CMSIS\5.7.0 -prefs=runtime.tools.CMSIS-5.7.0.path=C:\Users\amare\AppData\Local\Arduino15\packages\STMicroelectronics\tools\CMSIS\5.7.0 -verbose C:\Users\amare\Downloads\arduino-1.8.19-windows\arduino-1.8.19\examples\01.Basics\Blink\Blink.ino

Using board 'Nucleo_64' from platform in folder: C:\Users\amare\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.2.0

Using core 'arduino' from platform in folder: C:\Users\amare\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.2.0

Detecting libraries used...
recipe.preproc.macros pattern is missing
Error compiling for board Nucleo-64.

Regards,
Nagaraj

**Comment by fpistm** [comment]
Could you be more precise on your setup?
Arduino IDE version, selected board and option, sketch, ....

**Comment by nagarajgollar** [comment]
Hi,

Below are the details of my setup.

Board ; STM32F401

Arduino IDE version: 1.8.19

Sketch : Blink led from the example

![Board_details](https://user-images.githubusercontent.com/55886597/168471048-632b3cdd-5910-472c-ad42-1cabe181412e.jpg)

Regards,
Nagaraj

**Comment by fpistm** [comment]
Thank you.
Seems obvious as it works properly on our side.
I think you have an issue in your setup.
You should try om a fresh install to see if you reproduce it.

**Comment by fpistm** [comment]
Could you tell us which core version you used ? And where you get it ?
As far as I can see, all people having this error had a wrong setup.

**Comment by nagarajgollar** [comment]
Hi ,

i have used below examples
![image](https://user-images.githubusercontent.com/55886597/168569299-4a1513f0-429d-4c28-ae34-4a8376c7946d.png)

Regards,
Nagaraj

**Comment by fpistm** [comment]
This is library. I ask you the core version and which json file you used?
And try a clean installation please.

**Comment by nagarajgollar** [comment]
Hi,

I have used the below json file
https://raw.githubusercontent.com/stm32duino/BoardManagerFiles/main/package_stmicroelectronics_index.json

Arduino 1.9.19

Regards,
Nagaraj

**Comment by fpistm** [comment]
I guess it is 1.8.19.  Json file is the correct one.
All seems correct. Please try to reinstall in a fresh install to be sure all is fine.
This error is not linked to the core as it works well with this setup. You can also refer to the CI which is passed. I have no more clue for this. If you reproduce it you should open an issue on arduino ide GitHub.

**Comment by nagarajgollar** [comment]
Hi,

with fresh install of OS and arduino IDE its working fine. Thanks a lot 

Regards,
Nagaraj

**Comment by fpistm** [comment]
My guess is something breaks Arduino IDE cache or something like this. Anyway hard to tell why but by experience I already saw that several time.
