### ISSUE TITLE
STM32 Error

### ISSUE THREAD

**Issue by newguy** [stm32duino/BoardManagerFiles#45]
Hello,

I did try this with STM32, it did not work.

`
In file included from C:\Users\jave0\Documents\Arduino\libraries\FastLED\src/FastLED.h:43,
                 from C:\Users\jave0\Desktop\arduino prototype\ledtest\ledtest.ino:1:
C:\Users\jave0\Documents\Arduino\libraries\FastLED\src/led_sysdefs.h:55:2: error: #error "This platform isn't recognized by FastLED... yet.  See comments in FastLED/led_sysdefs.h for options."
   55 | #error "This platform isn't recognized by FastLED... yet.  See comments in FastLED/led_sysdefs.h for options."
      |  ^~~~~
In file included from C:\Users\jave0\Documents\Arduino\libraries\FastLED\src/platforms/avr/fastled_avr.h:6,
                 from C:\Users\jave0\Documents\Arduino\libraries\FastLED\src/platforms.h:41,
                 from C:\Users\jave0\Documents\Arduino\libraries\FastLED\src/FastLED.h:54,
                 from C:\Users\jave0\Desktop\arduino prototype\ledtest\ledtest.ino:1:
C:\Users\jave0\Documents\Arduino\libraries\FastLED\src/platforms/avr/clockless_trinket.h:6:10: fatal error: avr/interrupt.h: No such file or directory
    6 | #include <avr/interrupt.h> // for cli/se definitions
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board Nucleo-64.

`

**Comment by fpistm** [comment]
> #error "This platform isn't recognized by FastLED... yet. See comments in FastLED/led_sysdefs.h for options."
> | ^~~~~

As stated by the log, FastLED is not compatible with the STM32 core. You should ask to  FastLED repo
