### ISSUE TITLE
STM8 Error

### ISSUE THREAD

**Issue by newguy** [stm32duino/BoardManagerFiles#46]
Hello,

It did not work for STM8
`
unknown file type -DARDUINO_LIB_DISCOVERY_PHASE
exit status 1
Error compiling for board Nucleo_8L152R8.

`

**Comment by fpistm** [comment]
Hi
 You should use the last Arduino IDE.

**Comment by newguy** [comment]
How do you mean..I did use Arduino IDE

**Comment by fpistm** [comment]
I mean latest version. It is a known issue linked to Arduino. See https://github.com/stm32duino/Arduino_Core_STM8/issues/21

**Comment by newguy** [comment]
I have downgrade the version.. the new problem is the it refuse to take the Cosmic STM8 license..

**Comment by fpistm** [comment]
You have to register to cosmic
