### ISSUE TITLE
nucleo-f031k6 download problem

### ISSUE THREAD

**Issue by lv333ming** [stm32duino/BoardManagerFiles#47]
Follow the instructions here https://github.com/stm32duino/wiki/wiki/Getting-Started
nucleo-f031k6 unable to work properly

**Comment by fpistm** [comment]
Sorry for the delay missed that.

I've tested and it works.
Moreover you don't provide enough information in order to get help and issue is not on the correct repo.

**Comment by fpistm** [comment]
Just remember this:
https://github.com/stm32duino/Arduino_Core_STM32/pull/1787

So maybe it is your issue. Fix will be available with 2.4.0
