### ISSUE TITLE
Dear all , plz guide me.  ADC output  stm32f401cc black pill is noisy ,how it can be improved ....plz help Thanks

### ISSUE THREAD

**Issue by hakam007** [stm32duino/BoardManagerFiles#49]
my entire project is based on ADC Output but it produce noisy in serial plotter 
screen shot as below:
![noise ADC](https://user-images.githubusercontent.com/113838334/193216684-83151110-9c78-49dd-bc36-72ddf6fd72f9.png)
code:
![PROG NOISE](https://user-images.githubusercontent.com/113838334/193216779-1f4d88ac-79da-4a0b-b8b8-d823a4b2b7b1.png)

my entire project waste if ADC ouput is noisy , plz guide me ..thnaks

**Comment by fpistm** [comment]
Hi @hakam007,

please use the forum for such support: http://www.stm32duino.com

Here it is for issue with the boards manager file.

**Comment by hakam007** [comment]
yaah sure thanks bro!
