### ISSUE TITLE
Nucleo flasher windows bat does not work on all machines

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [stm32duino/BoardManagerFiles#5]
A fix for this is in the Arduino_Tools repo, but will not be rolled out via boards manager file until it has been tested on multiple machines e.g not just my W7 machine.

**Comment by fpistm** [comment]
I've tested it on Windows 8/10 and xp without any issue.
Note: I've renamed it "_massStorageCopy_" in order to be more generic.
