### ISSUE TITLE
The link provided is not working. I'm not able to download the boards manager for stm32

### ISSUE THREAD

**Issue by dhruv009dj** [stm32duino/BoardManagerFiles#51]
I'm having some issues with the link provided. I'm not able to download stm32 board manager

**Comment by rohit8vmu** [comment]
Yes, I am also facing the same issue. I am using Arduino 1.8.19. The Board Manager link I am using in the preference is:
https://github.com/stm32duino/BoardManagerFiles/raw/master/package_stmicroelectronics_index.json

This shows an error in downloading the package from the link.
I wonder what could be the correct JSON link?

**Comment by fpistm** [comment]
@rohit8vmu 
main not master:
https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json

@dhruv009dj 
And for error downloading check your proxy config.

**Comment by dhruv009dj** [comment]
@fpistm I have used no proxy in my settings. But the link is still not working.

**Comment by fpistm** [comment]
File is available on GitHub so it is valid. 
If you used a browser you should be able to download it.
Try to run arduino in debug mode or from a console to see if you have more info. 
Anyway I have no more idea as file and link are valid. I bet on Arduino or environment issue.

**Comment by fpistm** [comment]
And you only told that link is not valid. To get more support you should described precisely your setup, link you used,...
