### ISSUE TITLE
Can't download stm32 core

### ISSUE THREAD

**Issue by We8805** [stm32duino/BoardManagerFiles#52]
https://github.com/stm32duino/BoardManagerFiles/blob/main/package_stmicroelectronics_index.json
help me pls I add this link in to src (adruino ) but it's not working!!!

**Comment by fpistm** [comment]
You used the GitHub page link not the raw file link:
https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json

Refer to https://github.com/stm32duino/wiki/wiki/Getting-Started
