### ISSUE TITLE
issue when adding string to Arduino IDE

### ISSUE THREAD

**Issue by galagen8** [stm32duino/BoardManagerFiles#53]
When I added that string to Arduino IDE  Additional Boards Manager URLs:

https://raw.githubusercontent.com/stm32duino/BoardManagerFiles/main/package_stmicroelectronics_index.json

I got this message:

Some indexes could not be updated. Get "https://downloads.arduino.cc/packages/package_index.tar.bz2": proxyconnect tcp: dial tcp: lookup _: no such host: https://downloads.arduino.cc/packages/package_index.tar.bz2 Get "https://raw.githubusercontent.com/stm32duino/BoardManagerFiles/main/STM32/package_stm_index.json": proxyconnect tcp: dial tcp: lookup _: no such host: https://raw.githubusercontent.com/stm32duino/BoardManagerFiles/main/STM32/package_stm_index.json

What's wrong?

**Comment by fpistm** [comment]
Hi @galagen8 
this seems link to Arduino IDE no link with the link you add as even the package index from Arduino can't be downloaded due to proxy issue.
