### ISSUE TITLE
F412ZG Support

### ISSUE THREAD

**Issue by jizhanzhi1** [stm32duino/BoardManagerFiles#54]
Does this package supports F412ZG? I installed but didn't see board part number F412ZG on the Arduino.

**Comment by fpistm** [comment]
Hi,
you can add the generic support yourself, we already provides base files automatically generated:
https://github.com/stm32duino/Arduino_Core_STM32/tree/main/variants/STM32F4xx/F412Z(E-G)(J-T)

It misses the linker script, a default generic clock config and declare it in the boards.txt as described here:
https://github.com/stm32duino/Arduino_Core_STM32/wiki/Add-a-new-variant-%28board%29

Request already added to https://github.com/stm32duino/Arduino_Core_STM32/issues/722
Thanks this https://github.com/stm32duino/Arduino_Core_STM32/issues/1899
