### ISSUE TITLE
Legacy package indexes removed

### ISSUE THREAD

**Issue by matthijskooijman** [stm32duino/BoardManagerFiles#55]
Hey @fpistm, you removed the legacy package index (e.g. https://github.com/stm32duino/BoardManagerFiles/raw/dev/STM32/package_stm_index.json), I was still using that :-) We're still using a fork of the core based on 1.9.0, so I need to install your (unmodified) version to get the right tools to use our fork...

Any chance you could restore the index (preferably at the original URL)? Just reverting 6a4bcde seems to be enough for this.

**Comment by fpistm** [comment]
Hi @matthijskooijman 
you can use the master branch which kept legacy files.
https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json

I removed it from the main to avoid mistake (already had several feedback about this)

**Comment by matthijskooijman** [comment]
Works like a charm, thanks!
