### ISSUE TITLE
Board Manager File not working. 

### ISSUE THREAD

**Issue by vikramtamboli** [stm32duino/BoardManagerFiles#58]
https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json

when I enter the above link into Arduino board manager it does not work.
the boards are not listed in Arduino IDE

**Comment by fpistm** [comment]
Unfortunately, I can't help on this. It is link to Arduino IDE. Probably proxy configuration issue. The file is hosted on GH so it is available.

**Comment by vikramtamboli** [comment]
even if i try to open this file in web browser it does not work

![image](https://github.com/stm32duino/BoardManagerFiles/assets/16055034/54a5d28e-741b-4410-b609-a594eedfd7ec)

at least it should open in web browser.
if it's not accessible from web browser then how will it be available in Arduino

**Comment by fpistm** [comment]
Well it is available. Don't know why not for you. I can't help you on this. As stated it is hosted on github.
