### ISSUE TITLE
can't install board manager

### ISSUE THREAD

**Issue by boopathibooboo** [stm32duino/BoardManagerFiles#60]
"Error downloading https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json"

what is problem from my side I can't identify it. I have followed all the steps mentioned in the website exactly. but I got this error. And I also redoing the same get tired. please anyone guide me

**Comment by fpistm** [comment]
Unfortunately, I have no answer for you. This files is hosted on GitHub. The fact Arduino IDE can't download it relies on your configuration, network, proxy, ....
You could eventually file an issue on Arduino side.
