### ISSUE TITLE
Arduino_Core_STM32 submodule to version 2.7.1

### ISSUE THREAD

**Issue by P204503** [stm32duino/BoardManagerFiles#62]
Hellow,
I am trying to install Arduino_Core_STM32 submodule to version 2.7.1 in Arduino IDE version 1.81. and 2.2.1. In both cases, installing following the instructions https://docs.arduino.cc/learn/starting-guide/cores, the board is not added. Additionally, there is no information about errors.
Please let me know how I can add this module to the Arduino IDE.
With greeting
Piotr Mróz

**Comment by fpistm** [comment]
Hi @P204503 
You only have to add this link in thepreference:
https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json
Than it should appears in the Contributed menu in the IDE.
![image](https://github.com/stm32duino/BoardManagerFiles/assets/20641798/317bc001-634f-4855-8df5-b18f8273a891)

If it do not appears then it is an Arduino IDE issue.
