### ISSUE TITLE
The Additonal boards manager url not working

### ISSUE THREAD

**Issue by suray-mittal** [stm32duino/BoardManagerFiles#63]
Hi Everybody,

The URL https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json
for adding in 'Additional Boards Manager' in preferences section is not working. Kindly see this issue ASAP. Thanks in advance.

**Comment by fpistm** [comment]
Duplicate url is correct. See #58 and other. File is hosted by GitHub. Open an issue on Arduino ide side.
