### ISSUE TITLE
Some indexes could not be updated. 

### ISSUE THREAD

**Issue by 13992133** [stm32duino/BoardManagerFiles#65]
I get this error, how to fix it?

Some indexes could not be updated. Get "https://raw.githubusercontent.com/stm32duino/BoardManagerFiles/main/package_stmicroelectronics_index.json": dial tcp: lookup raw.githubusercontent.com: getaddrinfow: The requested name is valid, but no data of the requested type was found.: https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json

**Comment by fpistm** [comment]
Hi @13992133 
The file is simply hosted by GitHub. You probably have an issue with your network (proxy, antivir,...) or with Arduino IDE.
Unfortunately, we can't do nothing.
