### ISSUE TITLE
when i try to copy link

### ISSUE THREAD

**Issue by MochChen** [stm32duino/BoardManagerFiles#66]
Some indexes could not be updated. Get "https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json": unexpected EOF: https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json

**Comment by fpistm** [comment]
Hi @MochChen 
Unfortunately It is linked to Arduino IDE.
Try to clean the package json file.
